# Generated by Django 5.2 on 2025-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quranpage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
