# Generated by Django 5.2 on 2025-04-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_quranpage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khatm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='KhatmRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('khatm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.khatm')),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.quranpage')),
            ],
        ),
    ]
