# Generated by Django 5.2 on 2025-04-12 17:15

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_khatm_khatmrecords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatm',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='khatmrecords',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='khatm',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatm',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='khatmrecords',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='khatmrecords',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='khatmrecords',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.quranpage'),
        ),
    ]
