# Generated by Django 5.2 on 2025-04-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_khatm_options_alter_khatmrecords_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatm',
            options={'verbose_name': 'ختم'},
        ),
        migrations.AlterModelOptions(
            name='khatmrecords',
            options={'verbose_name': 'رکورد صفحه'},
        ),
    ]
