# Generated by Django 5.2 on 2025-05-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatm',
            options={'verbose_name': 'ختم', 'verbose_name_plural': 'ختم\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='khatmrecords',
            options={'verbose_name': 'رکورد صفحه', 'verbose_name_plural': 'رکوردهای صفحه'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'عضو', 'verbose_name_plural': 'اعضا'},
        ),
    ]
