# Generated by Django 5.2 on 2025-07-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_khatm_options_alter_khatmrecords_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EitaaOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
